name: "📝 New Newsletter Edition"
description: "Start a new monthly newsletter draft and generate the base file from template."
title: "Newsletter Draft: [Month Year]"
labels: ["newsletter", "automation"]
body:
  - type: input
    id: month
    attributes:
      label: Month
      description: Enter the month (e.g., May)
      placeholder: May
    validations:
      required: true

  - type: input
    id: year
    attributes:
      label: Year
      description: Enter the year (e.g., 2025)
      placeholder: 2025
    validations:
      required: true
